# Run with: python openai/openai_cot_thinking.py
import os
from dotenv import load_dotenv
from openai import OpenAI

# Load OPENAI_API_KEY from .env and create the SDK client.
load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Reuse one problem so the approaches are easy to compare.
PROBLEM = "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?"
REASONING_MODEL = "gpt-5-nano"  # Lowest-cost hosted OpenAI reasoning model.

# ── 1. Requested step-by-step explanation (works with any model) ──────────
# This does NOT enable a special hidden reasoning mode.
# It simply asks the model to show its reasoning in the visible answer.
# Useful for learning, but the reasoning text becomes part of the output.
print("=== Requested step-by-step explanation (gpt-4o-mini) ===")
explanation_response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "system",
            # This prompt requests a visible step-by-step explanation.
            # It is different from built-in reasoning configured through the API.
            "content": "Think step by step before giving your final answer.",
        },
        {"role": "user", "content": PROBLEM},
    ],
)
print(explanation_response.choices[0].message.content)

# ── 2. Built-in reasoning via the Responses API ────────────────────────────
# gpt-5-nano reasons internally before answering. reasoning.effort controls how
# much reasoning it performs; supported values depend on the selected model.
print(f"\n=== Built-in reasoning ({REASONING_MODEL}, effort=medium) ===")
thinking_response = client.responses.create(
    model=REASONING_MODEL,
    reasoning={"effort": "medium"},
    input=PROBLEM,
)

# output_text contains the final answer, not the model's raw internal reasoning.
# OpenAI does not return raw internal reasoning. Supported models can optionally
# return a reasoning summary, and usage reports the number of reasoning tokens.
print("Answer:", thinking_response.output_text)

# Token usage:
#   input      = tokens in the input you sent
#   reasoning  = hidden internal thinking tokens used by the reasoning model
#   output     = all output-side tokens, including hidden reasoning tokens
if (usage := thinking_response.usage) and usage.output_tokens_details:
    print(f"Tokens — input: {usage.input_tokens}, "
          f"reasoning: {usage.output_tokens_details.reasoning_tokens}, "
          f"output: {usage.output_tokens}")

# ── 3. Optional reasoning summary ──────────────────────────────────────────
# A summary is generated by the model; it is not the raw internal reasoning.
# Set this to True to make an additional API request and print the summary.
SHOW_REASONING_SUMMARY = False

if SHOW_REASONING_SUMMARY:
    summary_response = client.responses.create(
        model=REASONING_MODEL,
        reasoning={"effort": "medium", "summary": "auto"},
        input=PROBLEM,
    )

    print("\n=== Optional reasoning summary ===")
    for item in summary_response.output:
        if item.type == "reasoning":
            for summary_part in item.summary:
                print(summary_part.text)
    print("Answer:", summary_response.output_text)
